stages:
  - install_and_lint
  - build
  - test

variables:
  FRONTEND_DIR: src/frontend/vocca
  CARGO_HOME: "$CI_PROJECT_DIR/cargo"
  PROJECT_ID: "d3fa7677b00d83921f1b0a317cbba82a" # from wagmi

cache:
  key: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}
  paths:
    - src/frontend/vocca/node_modules/

before_script:
  #  For Frontend
  - touch .env.local # Ensure the file exists before building
  - echo "NEXT_PUBLIC_PROJECT_ID=$PROJECT_ID" >> .env.local # Append or create project id
  #End Frontend
  - export PATH="$CARGO_HOME/bin:$PATH"
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source "$CARGO_HOME/env"
  # Install circom, adjust the installation command as needed based on the correct circom structure
  - git clone https://github.com/iden3/circom.git
  - cd circom
  - cargo build --release
  # Assuming the binary is directly in the target/release after build
  - cargo install --path circom
  - cd ..

# for frontend
# merging the install and lint stages together
install_and_lint:
  stage: install_and_lint
  image: node:latest
  script:
    - cd $FRONTEND_DIR
    - npm install
    - npm install sharp
    - npm run lint
  only:
    changes:
      - src/frontend/**/*

build_project:
  stage: build
  image: node:latest
  script:
    - cd $FRONTEND_DIR
    - npm run build
  artifacts:
    paths:
      - src/frontend/vocca/.next/
  only:
    changes:
      - src/frontend/**/*  # Run this job only if there are changes in the src/frontend directory

test_verify_sig:
  stage: test
  script:
    - circom --version || echo "Circom not found"
    - npm install -g snarkjs
    - cd src/circuits
    - npm install
    - cd verify_sig
    - chmod +x test.sh
    - ./test.sh
  only:
    changes:
      - src/circuits/verify_sig/**/*
    refs:
      - master
      - development
      - merge_requests

test_verify_merkle:
  stage: test
  script:
    - circom --version || echo "Circom not found"
    - npm install -g snarkjs
    - cd src/circuits
    - npm install
    - cd verify_merkle
    - chmod +x test.sh
    - ./test.sh
  only:
    changes:
      - src/circuits/verify_merkle/**/*
    refs:
      - master
      - development
      - merge_requests

test_verify_single_tx:
  stage: test
  script:
    - circom --version || echo "Circom not found"
    - npm install -g snarkjs
    - cd src/circuits
    - npm install
    - cd verify_single_tx
    - chmod +x test.sh
    - ./test.sh
  only:
    changes:
      - src/circuits/verify_single_tx/**/*
    refs:
      - master
      - development
      - merge_requests

test_verify_multiple_tx:
  stage: test
  script:
    - circom --version || echo "Circom not found"
    - npm install -g snarkjs
    - cd src/circuits
    - npm install
    - cd verify_multiple_tx
    - chmod +x test.sh
    - ./test.sh
  only:
    changes:
      - src/circuits/verify_multiple_tx/**/*
    refs:
      - master
      - development
      - merge_requests

test_verify_withdrawal_sig:
  stage: test
  script:
    - circom --version || echo "Circom not found"
    - npm install -g snarkjs
    - cd src/circuits
    - npm install
    - cd verify_withdrawal_sig
    - chmod +x test.sh
    - ./test.sh
  only:
    changes:
      - src/circuits/verify_withdrawal_sig/**/*
    refs:
      - master
      - development
      - merge_requests
