stages:
  - build
  - test

variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/circuit-tester:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Stage for building the Docker image
build_image:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
  only:
    - master
    - merge_requests

# Stage for running tests on the `verify_sig` circuit
test_verify_sig:
  stage: test
  script:
    - docker pull $DOCKER_IMAGE_NAME
    - docker run --rm $DOCKER_IMAGE_NAME verify_sig
  only:
    - master
    - merge_requests
