stages:
  - test

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/cargo"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

cache:
  paths:
    - $CARGO_HOME/bin
    - $CARGO_HOME/registry
    - .npm
    - node_modules
    - src/circuits/node_modules
    - src/circuits/verify_sig/node_modules

before_script:
  - export PATH="$CARGO_HOME/bin:$PATH"
  - if [ ! -f "$CARGO_HOME/bin/circom" ]; then
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
      source "$CARGO_HOME/env" &&
      git clone https://github.com/iden3/circom.git &&
      cd circom &&
      cargo build --release &&
      cargo install --path .;
    fi
  - npm config set cache .npm --global
  - npm install -g snarkjs

test_verify_sig:
  stage: test
  script:
    - circom --version || echo "Circom not found"
    - cd src/circuits
    - npm install
    - cd verify_sig
    - chmod +x test.sh
    - ./test.sh
  only:
    - master
    - development
    - merge_requests
