stages:
  - test

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/cargo"

before_script:
  - export PATH="$CARGO_HOME/bin:$PATH"
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source "$CARGO_HOME/env"
  # Install circom, adjust the installation command as needed based on the correct circom structure
  - git clone https://github.com/iden3/circom.git
  - cd circom
  - cargo build --release
  # Assuming the binary is directly in the target/release after build
  - cargo install --path circom
  - cd ..

test_verify_sig:
  stage: test
  script:
    - circom --version || echo "Circom not found"
    - npm install -g snarkjs
    - cd src/circuits
    - npm install
    - cd  verify_sig
    - chmod +x test.sh
    - ./test.sh
  only:
    - master
    - development
    - merge_requests


test_verify_merkle:
  stage: test
  script:
    - circom --version || echo "Circom not found"
    - npm install -g snarkjs
    - cd src/circuits
    - npm install
    - cd  verify_merkle
    - chmod +x test.sh
    - ./test.sh
  only:
    - master
    - development
    - merge_requests
