stages:
  - prepare
  - test

cache:
  paths:
    - node_modules/
    - $HOME/.cargo/bin/
    - $HOME/.cargo/registry/
    - circom/target/

before_script:
  - export PATH="$HOME/.cargo/bin:$PATH"

prepare_circom:
  stage: prepare
  script:
    - which circom || (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y)
    - source $HOME/.cargo/env
    - if [ ! -f "$HOME/.cargo/bin/circom" ]; then
        git clone https://github.com/iden3/circom.git && cd circom/circom && cargo build --release;
        cargo install --path circom;
      fi
  artifacts:
    paths:
      - $HOME/.cargo/bin/circom
  only:
    - master
    - development
    - merge_requests


test_verify_sig:
  stage: test
  script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - which circom || echo "Circom not found"
    - cd src/circuits/verify_sig
    - npm install
    - chmod +x test.sh
    - ./test.sh
  dependencies:
    - prepare_circom
  only:
    - master
    - development
    - merge_requests


