stages:
  - install
  - lint
  - build
  - test


# defining path to the directory so jobs can find package.json
variables:
  FRONTEND_DIR: src/frontend/vocca
  CARGO_HOME: "$CI_PROJECT_DIR/cargo"

<<<<<<< HEAD
<<<<<<< HEAD
# use cache instead of artifacts for node_modules to save space and share it across the jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}
  paths:
    - src/frontend/vocca/node_modules/

# change to directory
=======
cache:
  paths:
    - $CARGO_HOME/registry
    - $CARGO_HOME/git
    - circom/target
    - src/circuits/node_modules/

>>>>>>> cf6639d (last commit works --try to optimise)
=======
>>>>>>> 405eb5e (Revert "last commit works --try to optimise")
before_script:
  - export PATH="$CARGO_HOME/bin:$PATH"
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source "$CARGO_HOME/env"
  # Install circom, adjust the installation command as needed based on the correct circom structure
  - git clone https://github.com/iden3/circom.git
  - cd circom
  - cargo build --release
  # Assuming the binary is directly in the target/release after build
  - cargo install --path circom
  - cd ..

  test_verify_sig:
  stage: test
  script:
    - circom --version || echo "Circom not found"
    - npm install -g snarkjs
    - cd src/circuits
    - npm install
<<<<<<< HEAD
<<<<<<< HEAD
=======
    - npx snarkjs --help || echo "SnarkJS not found"
>>>>>>> cf6639d (last commit works --try to optimise)
    - cd verify_sig
=======
    - cd  verify_sig
>>>>>>> 405eb5e (Revert "last commit works --try to optimise")
    - chmod +x test.sh
    - ./test.sh
  only:
    changes:
      - src/circuits/verify_sig/**/*
    refs:
      - master
      - development
      - merge_requests

test_verify_merkle:
  stage: test
  script:
    - circom --version || echo "Circom not found"
    - npm install -g snarkjs
    - cd src/circuits
    - npm install
    - cd verify_merkle
    - chmod +x test.sh
    - ./test.sh
  only:
    changes:
      - src/circuits/verify_merkle/**/*
    refs:
      - master
      - development
      - merge_requests

test_verify_single_tx:
  stage: test
  script:
    - circom --version || echo "Circom not found"
    - npm install -g snarkjs
    - cd src/circuits
    - npm install
    - cd verify_single_tx
    - chmod +x test.sh
    - ./test.sh
  only:
    changes:
      - src/circuits/verify_single_tx/**/*
    refs:
      - master
      - development
      - merge_requests

install_dependencies:
  stage: install
  image: node:latest
  script:
    - cd $FRONTEND_DIR
    - npm install # npm ci alternative, as it was failing

lint_code:
  stage: lint
  image: node:latest
  script:
    - cd $FRONTEND_DIR
    - npm run lint

# Tests will be added later on in the development process
# run_tests:
#   stage: test
#   image: node:latest
#   script:
#     - npm run test
#   dependencies:
#     - install_dependencies

build_project:
  stage: build
  image: node:latest
  script:
    - cd $FRONTEND_DIR
    - npm run build
  artifacts:
    paths:
      - src/frontend/vocca/.next/
