stages:
  - install
  - lint
  - build

# defining path to the directory so jobs can find package.json
variables:
  FRONTEND_DIR: src/frontend/vocca
# change to directory
before_script:
  - cd $FRONTEND_DIR

install_dependencies:
  stage: install
  image: node:latest
  script:
    - npm install # npm ci alternative, as it was failing
  artifacts:
    paths:
      - src/frontend/vocca/node_modules/

lint_code:
  stage: lint
  image: node:latest
  script:
    - npm run lint
  dependencies:
    - install_dependencies

# Tests will be added later on in the development process
# run_tests:
#   stage: test
#   image: node:latest
#   script:
#     - npm run test
#   dependencies:
#     - install_dependencies

build_project:
  stage: build
  image: node:latest
  script:
    - npm run build
  artifacts:
    paths:
      - src/frontend/vocca/.next/
  dependencies:
    - install_dependencies
