[profile.default]
solc = "0.8.0"
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
local = "${PROVIDER_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
